### ISSUE TITLE
Add Rain Guage UI

### ISSUE THREAD

**Issue by subins2000** [thetronjohnson/wowfe#3]
A form to add/edit a new rain guage :
* Name
* Location
  * Pincode
  * Coordinates
  * Place name. This placename shouldbe otainable from http://www.geonames.org/search.html?q=Kunnamkulam
  * District
  * State
  * Country

**Comment by thetronjohnson** [comment]
@subins2000 Ith user profile ilek alle

**Comment by thetronjohnson** [comment]
Oru test comment webhook wrk ayo enn nokkan
